import test from 'node:test';
import assert from 'node:assert/strict';
import { blankState, validateState, parseBackup, newEvent, newTheme, newRoute, newNode,
  demoState, sortedEvents, budgetUsage, descendants, removeEntity, periodBounds,
  progressFor, actionReadiness, validDate, addDays, clone } from '../src/domain.mjs';
const state = () => validateState(demoState());
const action = (overrides = {}) => ({ ...newNode(), id:'action-test', startDate:'2026-09-01', ...overrides });
const log = (amount, overrides = {}) => ({ id:`log-${Math.random().toString(36).slice(2)}`, nodeId:'action-test', date:'2026-09-08', amount, mode:'full', direction:'supports', note:'', decision:'keep', ...overrides });

test('blank and fictional demo satisfy complete schema',()=>{assert.equal(validateState(blankState()).version,1); assert.equal(state().events.length,13);});
test('validation clones input and strips unknown properties',()=>{const s=state();s.unknown='discard';const v=validateState(s);assert.equal(v.unknown,undefined);v.events[0].title='different';assert.notEqual(v.events[0].title,s.events[0].title);});
test('unrated energy remains null and zero remains zero',()=>{const s=blankState();s.events=[newEvent()];assert.equal(validateState(s).events[0].energy,null);s.events[0].energy=0;assert.equal(validateState(s).events[0].energy,0);});
test('energy refuses strings, fractions and out of range',()=>{for(const energy of ['2',NaN,Infinity,-11,11,1.5]){const s=blankState();s.events=[{...newEvent(),energy}];assert.throws(()=>validateState(s));}});
test('three monthly slots allocated in order',()=>{const s=blankState();for(let i=1;i<=3;i++){const e=newEvent(3,s.events);assert.equal(e.order,i);s.events.push(e);}assert.equal(validateState(s).events.length,3);s.events.push(newEvent(3,s.events));assert.throws(()=>validateState(s),/最多 3/);});
test('background does not consume monthly slot',()=>{const s=blankState();for(let i=0;i<3;i++)s.events.push(newEvent(1,s.events));s.events.push(newEvent(1,s.events,'background'));assert.equal(validateState(s).events.length,4);});
test('background limit is enforced',()=>{const s=blankState();for(let i=0;i<51;i++)s.events.push(newEvent(1,[],'background'));assert.throws(()=>validateState(s),/50/);});
test('duplicate monthly order rejected',()=>{const s=blankState();s.events=[newEvent(),newEvent()];assert.throws(()=>validateState(s),/順序重複/);});
test('duplicate entity identifiers rejected',()=>{const s=state();s.events[1].id=s.events[0].id;assert.throws(()=>validateState(s),/識別碼/);});
test('unsafe identifiers rejected; user prose is preserved as data',()=>{const s=state();s.events[0].title='<img src=x onerror=alert(1)>';assert.equal(validateState(s).events[0].title,s.events[0].title);s.events[0].id='" onclick="evil';assert.throws(()=>validateState(s));});
test('missing fields and wrong booleans rejected',()=>{const s=state();delete s.events[0].private;assert.throws(()=>validateState(s));});
test('unknown backup version, malformed JSON, oversized content rejected',()=>{assert.throws(()=>parseBackup('{'));assert.throws(()=>parseBackup(JSON.stringify({...state(),version:2})));assert.throws(()=>parseBackup(' '.repeat(2*1024*1024+1)));});
test('JSON export/import round trip',()=>{const s=state();assert.deepEqual(parseBackup(JSON.stringify(s)),s);});
test('dangling event, theme and route relations rejected',()=>{for(const mutate of [s=>s.themes[0].eventIds.push('missing'),s=>s.routes[0].themeId='missing',s=>s.nodes[0].routeId='missing']){const s=state();mutate(s);assert.throws(()=>validateState(s));}});
test('duplicate many-to-many links rejected',()=>{const s=state();s.themes[0].eventIds.push(s.themes[0].eventIds[0]);assert.throws(()=>validateState(s),/重複關聯/);});
test('objective tree rejects cycles',()=>{const s=blankState();const a=newNode('objective'),b=newNode('objective',a.id);a.parentId=b.id;s.nodes=[a,b];assert.throws(()=>validateState(s),/循環/);});
test('action cannot be parent',()=>{const s=blankState();const a=newNode(),b=newNode('action',a.id);s.nodes=[a,b];assert.throws(()=>validateState(s),/上層/);});
test('objective cannot be nested under result',()=>{const s=blankState();const a=newNode('result'),b=newNode('objective',a.id);s.nodes=[a,b];assert.throws(()=>validateState(s),/方向只能/);});
test('eight hierarchy levels allowed, nine rejected',()=>{const s=blankState();for(let i=0;i<8;i++)s.nodes.push(newNode('objective',s.nodes.at(-1)?.id??''));validateState(s);s.nodes.push(newNode('action',s.nodes.at(-1).id));assert.throws(()=>validateState(s),/8 層/);});
test('removing event detaches references without deleting themes',()=>{const s=state(),id=s.themes[0].eventIds[0];const v=removeEntity(s,'events',id);assert.equal(v.themes.length,s.themes.length);assert.ok(v.themes.every(t=>!t.eventIds.includes(id)));assert.ok(s.events.some(e=>e.id===id));});
test('removing theme retains routes and plans',()=>{const s=state(),v=removeEntity(s,'themes',s.themes[0].id);assert.equal(v.routes.length,s.routes.length);assert.equal(v.nodes.length,s.nodes.length);assert.ok(v.routes.every(r=>r.themeId!==s.themes[0].id));});
test('removing route retains action plans',()=>{const s=state(),r=s.routes[0];s.nodes[1].routeId=r.id;const v=removeEntity(s,'routes',r.id);assert.equal(v.nodes.length,s.nodes.length);assert.equal(v.nodes[1].routeId,'');});
test('subtree deletion also removes related reviews only',()=>{const s=blankState(),o=newNode('objective'),a={...action(),parentId:o.id},b=newNode();s.nodes=[o,a,b];s.reviews=[log(1)];assert.deepEqual([...descendants(s.nodes,o.id)], [o.id,a.id]);const v=removeEntity(s,'nodes',o.id);assert.equal(v.nodes.length,1);assert.equal(v.reviews.length,0);});
test('unselected alternatives cost nothing; stress changes only time capacity',()=>{const s=blankState();s.routes=[{...newRoute(),selected:true,hours:4,money:1000,energy:2},{...newRoute(),hours:99,money:99999,energy:99}];assert.deepEqual(budgetUsage(s).totals,{hours:4,money:1000,energy:2});assert.deepEqual(budgetUsage(s,.5).over,['hours']);assert.equal(budgetUsage(s,.5).available.money,5000);assert.equal(s.budget.hours,6);});
test('chronological ordering preserves original and excludes backgrounds',()=>{const a={...newEvent(5),order:2},b={...newEvent(1)},c=newEvent(1,[],'background');const original=[a,c,b];assert.deepEqual(sortedEvents(original).map(x=>x.id),[b.id,a.id]);assert.equal(original[0],a);});
test('calendar weeks begin Monday across year boundary',()=>{assert.deepEqual(periodBounds('week','2026-01-01'),{first:'2025-12-29',last:'2026-01-04'});});
test('calendar months respect leap year',()=>{assert.equal(periodBounds('month','2024-02-10').last,'2024-02-29');assert.equal(periodBounds('month','2025-02-10').last,'2025-02-28');});
test('valid dates reject normalized impossible dates',()=>{assert.equal(validDate('2025-02-29'),false);assert.equal(validDate('2024-02-29'),true);assert.equal(validDate('2026-13-01'),false);assert.equal(addDays('2025-12-31',1),'2026-01-01');});
test('review date cannot precede action start',()=>{const s=blankState();s.nodes=[action({startDate:'2026-09-08',reviewDate:'2026-09-01'})];assert.throws(()=>validateState(s),/早於/);});
test('habit sums full records only',()=>{const p=progressFor(action({target:3}),[log(1),log(2),log(4,{mode:'minimum'})],'2026-09-08');assert.equal(p.full,3);assert.equal(p.minimum,4);assert.equal(p.met,true);});
test('outcome uses latest snapshot, not sum',()=>{const p=progressFor(action({aggregation:'latest',target:3000,period:'once'}),[log(1500,{date:'2026-09-07'}),log(3000)],'2026-09-08');assert.equal(p.full,3000);});
test('future, previous period and pre-start entries excluded',()=>{const p=progressFor(action({startDate:'2026-09-08'}),[log(1),log(7,{date:'2026-09-07'}),log(5,{date:'2026-09-09'}),log(20,{date:'2026-08-31'})],'2026-09-08');assert.equal(p.full,1);});
test('no data is not a successful boundary',()=>{const p=progressFor(action({comparator:'atMost',target:1}),[],'2026-09-08');assert.equal(p.met,null);assert.equal(p.hasData,false);});
test('minimum-only or reflection-only does not count as full evidence',()=>{for(const record of [log(1,{mode:'minimum'}),log(0,{mode:'reflection'})])assert.equal(progressFor(action(),[record],'2026-09-08').met,null);});
test('boundary evaluates upper limit, not higher-is-better',()=>{const n=action({comparator:'atMost',target:1});assert.equal(progressFor(n,[log(1)],'2026-09-08').met,true);assert.equal(progressFor(n,[log(2)],'2026-09-08').met,false);});
test('exact target uses equality',()=>{const n=action({comparator:'exactly',target:2});assert.equal(progressFor(n,[log(3)],'2026-09-08').met,false);});
test('execution and direction remain separate',()=>{const p=progressFor(action({target:1}),[log(1,{direction:'drains'})],'2026-09-08');assert.equal(p.met,true);assert.equal(p.directionSupport,0);});
test('reflection/missed cannot forge numeric completion',()=>{const s=blankState();s.nodes=[action()];s.reviews=[log(1,{mode:'missed'})];assert.throws(()=>validateState(s),/不能記入/);});
test('review cannot attach to objective',()=>{const s=blankState(),o=newNode('objective');s.nodes=[o];s.reviews=[log(1,{nodeId:o.id})];assert.throws(()=>validateState(s),/回顧只能/);});
test('readiness reports actionable omissions without gating values',()=>{const n=action({reviewDate:''});assert.equal(actionReadiness(n).length,4);Object.assign(n,{acceptance:'完成一次',trigger:'吃完晚餐',reviewDate:'2026-09-22',fallback:'改做縮小版'});assert.deepEqual(actionReadiness(n),[]);});
