import {STORAGE_KEY,createWorkspace,newEvent,newTheme,newDirection,newRoute,newAction,uid,today,afterDays,chronology,chartPoints,ratedEvents,upsertEvent,resourceStatus,deleteEntity,validateWorkspace,parseBackup,makeDemo} from './model.js';

const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0m5 4 3-7 5-2-3 7z',cards:'M5 5h12v16H5zM9 2h11l2 15M8 9h6M8 13h5',wave:'M2 15l5-7 5 11 5-15 5 9',theme:'M8 6a3 3 0 1 0-6 0 3 3 0 0 0 6 0m14 0a3 3 0 1 0-6 0 3 3 0 0 0 6 0M15 19a3 3 0 1 0-6 0 3 3 0 0 0 6 0M6 9l5 7m7-7-5 7',route:'M5 3v13a5 5 0 0 0 5 5h2M5 12h9a5 5 0 0 0 5-5V3M2 18l3 3 3-3',flag:'M5 22V3c5-5 9 5 14 0v10c-5 5-9-5-14 0',review:'M3 10a9 9 0 0 1 15-6l3 3M21 2v5h-5M21 14A9 9 0 0 1 6 20l-3-3M3 22v-5h5',leaf:'M3 20C0 8 10 3 22 2c-1 13-7 22-19 18M3 20 16 8',lock:'M6 10h12v11H6zM9 10V6a3 3 0 0 1 6 0v4m-3 4v3',download:'M12 2v13m-5-5 5 5 5-5M4 16v5h16v-5',plus:'M12 5v14M5 12h14',arrow:'M4 12h16m-6-6 6 6-6 6',edit:'m4 16-1 5 5-1L20 8l-4-4zM14 6l4 4',close:'m5 5 14 14M5 19 19 5',check:'m5 12 4 4L19 6',clock:'M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0m9-5v5l4 2',help:'M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0m6-3c0-4 6-4 6 0 0 2-3 2-3 5m0 3v1',eye:'M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12m8 0a3 3 0 1 0 6 0 3 3 0 0 0-6 0',trash:'M4 6h16M8 6V3h8v3M6 6l1 15h10l1-15M10 10v7m4-7v7'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.leaf}"/></svg>`;
const stages=[['開始','先讀玩法，再慢慢開始','home'],['拾起片刻','事實，不急著下結論','cards'],['看見起伏','能量、情緒與回應空間','wave'],['發現線索','主題是一種假設','theme'],['打開可能','比較不同的生活路線','route'],['帶走實驗','行動，也可以很小','flag'],['回來看看','允許調整與停止','review']];
const planned={unknown:'還不確定',planned:'安排好的',unexpected:'意外發生',mixed:'兩者都有'};
const controls={unknown:'還不知道',direct:'自己可以行動',together:'需要一起協作',adapt:'調適／尋求支持'};
const kinds={more:'再多一點',less:'少做一點',different:'換一種做法',observe:'先觀察',other:'自己的路'};
const actionTypes={habit:'習慣／行為',outcome:'成果目標 · OKR',project:'體驗／專案',boundary:'生活界線／上限',process:'固定流程'};
const periods={day:'每天',week:'每週',month:'每月',year:'每年',trial:'這次實驗期間'};
const statuses={trying:'正在試試',continue:'繼續',adjust:'調整',pause:'暫停',stop:'停止'};
const emotions=['安心','自在','喜悅','期待','好奇','投入','溫暖','平靜','釋然','勇敢','疲憊','焦慮','失落','委屈','生氣','孤單','不安','無力','矛盾','還說不上來'];
const values=['自由','連結','探索','表達','安定','照顧','精進','創造','界線','留白','真誠','玩心'];
const prompts=['除了增加一件事，少做什麼也能支持這個方向？','先不要選第一個答案。還有哪條完全不同的路？','假設可用時間減半，你會留下哪一小部分？','不花錢的版本，可以怎麼做？','誰能提供支持，而不只是監督你？','暫時不改變，先觀察兩週，會學到什麼？'];
let w=createWorkspace(),page=0,month=1,demo=false,saved=null,stress=false,promptIndex=0,themeMode='bottom',memoryWarning='',conflict=false,hideAll=false;
let envelope={version:1,activeYear:w.year,years:{}}, storageStamp='', lastFocus=null;
try{
  const raw=localStorage.getItem(STORAGE_KEY); storageStamp=raw||'';
  if(raw){const e=JSON.parse(raw);if(e.version!==1||!e.years||!Number.isInteger(e.activeYear)||e.activeYear<1900||e.activeYear>2100)throw Error('格式');
    const years={};for(const [year,data] of Object.entries(e.years)){const valid=validateWorkspace(data);if(String(valid.year)!==year)throw Error('年份');years[year]=valid;}
    envelope={version:1,activeYear:e.activeYear,years};w=years[e.activeYear]||createWorkspace(e.activeYear);}
  const probe=`${STORAGE_KEY}:probe`;localStorage.setItem(probe,'1');localStorage.removeItem(probe);
}catch{memoryWarning='目前無法讀取或寫入本機儲存。原始儲存內容不會被覆蓋；請用備份匯出保留這次的記錄。';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function persist(){
  w.updatedAt=new Date().toISOString(); if(demo)return;
  envelope.activeYear=w.year;envelope.years[w.year]=structuredClone(w);
  if(memoryWarning||conflict)return;
  try{const current=localStorage.getItem(STORAGE_KEY)||'';if(current!==storageStamp){conflict=true;return;}
    storageStamp=JSON.stringify(envelope);localStorage.setItem(STORAGE_KEY,storageStamp);
  }catch{memoryWarning='瀏覽器無法儲存；目前只在記憶體中。離開前請先匯出備份。';}
}
function update(fn){fn();persist();render(false);}
const btn=(text,act,cls='',data='')=>`<button class="btn ${cls}" type="button" data-act="${act}" ${data}>${text}</button>`;
const tag=t=>`<span class="tag">${esc(t)}</span>`;
const empty=(title,body,button='')=>`<div class="empty">${icon('leaf')}<h3>${title}</h3><p>${body}</p>${button}</div>`;
const note=t=>`<div class="note">${icon('leaf')}<div>${t}</div></div>`;
const heading=(n,title,desc,extra='')=>`<header class="page-heading"><div><div class="eyebrow">${n}</div><h1>${title}</h1><p>${desc}</p></div>${extra}</header>`;
const next=(p,text)=>`<div class="page-end"><span>${icon('lock')} 可以跳過、留白，也可以隨時回來。</span>${btn(`${text} ${icon('arrow')}`,'nav','primary',`data-page="${p}"`)}</div>`;
const visibleTitle=e=>(hideAll||e.private)?'已遮住的片刻':e.title;
function render(scroll=true){
  const focused=document.activeElement;
  const selector=focused?.id?`#${CSS.escape(focused.id)}`:focused?.dataset.act?`[data-act="${CSS.escape(focused.dataset.act)}"]${focused.dataset.id?`[data-id="${CSS.escape(focused.dataset.id)}"]`:''}`:focused?.dataset.change?`[data-change="${CSS.escape(focused.dataset.change)}"]`:null;
  $('#app').innerHTML=`<aside class="sidebar"><a href="#" class="brand" data-act="nav" data-page="0"><span class="brand-icon">${icon('wave')}</span><span>拾光<small>LIFE ATLAS</small></span></a><p class="brand-caption">一場與自己的年度對話</p><nav aria-label="探索旅程">${stages.map((s,i)=>`<button type="button" data-act="nav" data-page="${i}" class="nav-item ${page===i?'active':''}" ${page===i?'aria-current="step"':''}>${icon(s[2])}<span>${s[0]}<small>${s[1]}</small></span></button>`).join('')}</nav><div class="sidebar-bottom">${icon('leaf')}<p>沒有標準答案。<br>不需要把人生整理得很漂亮。</p><hr><small>${icon('lock')} 資料留在這台裝置<br>無帳號・無上傳・無排行榜</small></div></aside>
  <div class="workspace"><header class="topbar"><div class="breadcrumb">我的探索桌 <span>/</span> ${btn(`${w.year} ${icon('edit')}`,'year','quiet',`aria-label="切換回顧年份，目前 ${w.year}"`)} ${demo?tag('示範旅程'):''}</div><div class="top-actions"><span class="save-state">${demo?'示範不會寫入儲存':conflict?'另一分頁有更新':memoryWarning?'請先備份':w.updatedAt?'已存在這台裝置':'準備開始'}</span>${btn(icon(hideAll?'eye':'lock'),'privacy','icon-btn',`aria-label="${hideAll?'取消全畫面遮罩':'遮住全部內容'}"`)}${btn(`${icon('download')} <span>備份與匯出</span>`,'backup','outline',`aria-label="備份與匯出"`)}</div></header>
  ${memoryWarning?`<div class="banner warning" role="alert">${memoryWarning}</div>`:''}${conflict?`<div class="banner warning" role="alert">另一個分頁已更新資料。已暫停自動儲存以免互相覆蓋。${btn('處理資料衝突','conflict','quiet')}</div>`:''}${demo?`<div class="banner demo-banner">示範桌上的故事都是虛構的；你的個人資料仍保留著。${btn('回到我的探索桌','exit-demo','quiet')}</div>`:''}
  <main id="main" tabindex="-1">${hideAll?empty('內容已遮住','這只是畫面遮罩，不是加密或密碼鎖。',btn('回到探索桌','privacy','primary')):[home,moments,reflection,themes,options,actions,reviews][page]()}</main><footer><span>拾光 Life Atlas · 事件是素材，主題是假設，行動是實驗。</span>${btn('玩法與界線','help','quiet')}<span>v0.2 · local-first</span></footer></div>`;
  if(!scroll&&selector&&!$('#dialog').open)$(selector)?.focus({preventScroll:true});
  if(scroll){window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});document.querySelector('.nav-item.active')?.scrollIntoView({block:'nearest',inline:'center'});}
}
function home(){return `<section class="hero"><div><div class="eyebrow">A LITTLE SPACE, JUST FOR YOU</div><h1>把這一年攤開，<br>拾起<span>你在乎的事。</span></h1><p>不用急著成為更好的自己。<br>先看見走過的片刻，再為接下來的生活，<br>留一個小小的可能。</p><div class="button-row">${btn(`開始拾起片刻 ${icon('arrow')}`,'nav','primary',`data-page="1"`)}${btn('先玩一輪示範','demo','outline')}</div><small class="muted">${icon('lock')} 無需登入。記錄不會傳到伺服器。</small></div><div class="hero-board" aria-hidden="true"><div class="board-label">MY YEAR, MY WAY <span>${w.year}</span></div><svg class="hero-line" viewBox="0 0 480 330"><path d="M15 215 110 145 218 270 325 74 450 129" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="5 6"/><circle cx="218" cy="270" r="5" fill="currentColor"/><circle cx="325" cy="74" r="5" fill="currentColor"/></svg><div class="paper paper-green"><small>一個讓我充電的片刻</small><p>一起做<br>平常的小事</p><hr><small>連結 · 陪伴</small></div><div class="paper paper-peach"><small>一個還沒想明白的片刻</small><p>也允許自己<br>慢一點</p><hr><small>留白，不是空白。</small></div><span class="board-note">✧ 沒有高分人生<br>　只有你的故事</span></div></section>
  <div class="stats">${[[w.events.length,'個被拾起的片刻'],[w.themes.length,'條正在浮現的線索'],[w.actions.length,'個想帶走的小實驗']].map(([n,t])=>`<div><strong>${String(n).padStart(2,'0')}</strong><span>${t}</span></div>`).join('')}<p>這不是得分。<br>只是你留下的足跡。</p></div>
  <section class="journey"><div class="eyebrow">HOW THE JOURNEY UNFOLDS</div><h2>從一年的片刻，到一個小小的下一步。</h2><div class="journey-grid">${stages.slice(1).map((s,i)=>`<button class="journey-card" data-act="nav" data-page="${i+1}"><small>0${i+1}</small>${icon(s[2])}<h3>${s[0]}</h3><p>${s[1]}</p></button>`).join('')}</div></section>${note('<b>你的界線，也是規則。</b> 可以留白、遮住卡片、不分享，或決定今年不新增目標。這是反思工具，不是心理評量或治療。')}`;}
function eventCard(e,reflect=false){e={...e,energy:w.basis==='now'?(e.energyNow??null):e.energy};return `<article class="event-card ${e.energy===null?'neutral':e.energy>=0?'positive':'negative'}"><div class="card-top"><span class="overline">${e.background?'日常背景':`${e.month} 月 · ${e.order}`}</span>${btn(icon('edit'),reflect?'reflect-event':'event','icon-btn',`data-id="${e.id}" aria-label="${reflect?'標記感受':'編輯事件'}：${esc(visibleTitle(e))}"`)}</div><h3>${esc(visibleTitle(e))||'還沒命名'}</h3>${e.private?'<p class="muted">內容已遮住；編輯時才顯示。</p>':`<p>${esc(e.fact)||'暫時只記下一個片刻。'}</p>`}<div class="tags">${e.energy===null?tag('尚未標記能量'):tag(`${e.energy>0?'+':''}${e.energy} 能量`)}${tag(planned[e.planned])}${e.private?icon('lock'):e.emotions.map(tag).join('')}</div>${reflect&&!e.private?`<small>${esc(controls[e.control])}${e.meaning?` · ${esc(e.meaning)}`:''}</small>`:''}</article>`;}
function moments(){const ev=w.events.filter(e=>!e.background&&e.month===month);return `${heading('01 · OBJECTIVE','先拾起片刻，不急著解釋。','先寫發生了什麼，再到下一站標記感受。每月 0–3 張，沒有事件的月份也可以留白。',btn(`${icon('plus')} 新增片刻`,'event','primary',ev.length>=3?'disabled':''))}
  <div class="prompt-strip">${icon('cards')}<span><b>給回憶一個線索</b>　翻翻行事曆、照片或訊息。誰在場？發生了什麼？把「可觀察的事實」和「我的解讀」暫時分開。</span></div>
  <div class="months" role="group" aria-label="選擇月份">${Array.from({length:12},(_,i)=>`<button class="month ${month===i+1?'selected':''}" data-act="month" data-month="${i+1}" aria-pressed="${month===i+1}"><b>${i+1}<small>月</small></b><span>${'●'.repeat(w.events.filter(e=>!e.background&&e.month===i+1).length)||'○'}</span></button>`).join('')}</div>
  <div class="section-title"><h2>${String(month).padStart(2,'0')} 月的片刻</h2><span>${ev.length} / 3 張 · 可以留白</span></div><div class="card-grid">${ev.sort((a,b)=>a.order-b.order).map(e=>eventCard(e)).join('')}${ev.length<3?`<button class="add-card" data-act="event">${icon('plus')}<span>${ev.length?'再拾起一個片刻':'這個月，有什麼還留在心裡？'}</span><small>一件大事，也可以是一件小事</small></button>`:''}</div>
  <section class="section-space"><div class="section-title"><div><h2>那些一直都在的日常</h2><p>通勤、練舞、照顧責任……不必是大事，也可能影響整年。</p></div>${btn(`${icon('plus')} 日常背景`,'background','outline')}</div><div class="card-grid">${w.events.filter(e=>e.background).map(e=>eventCard(e)).join('')}</div></section>${next(2,'看見起伏')}`;}
function curve(){const points=chartPoints(ratedEvents(w));return `<div class="chart-scroll" tabindex="0" aria-label="年度能量曲線，可橫向捲動；下方提供相同事件的文字卡片"><svg class="energy-chart" viewBox="0 0 1010 400" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">${w.year} 年事件能量曲線</title><desc id="chart-desc">橫軸一到十二月，縱軸負十到正十。沒有標記能量的事件不繪製。連線只表示事件順序，不是連續情緒量測。</desc>${[-10,-5,0,5,10].map(n=>`<line x1="45" y1="${190-n*13}" x2="985" y2="${190-n*13}" class="${n===0?'zero':'grid-line'}"/><text x="12" y="${195-n*13}">${n>0?'+':''}${n}</text>`).join('')}${Array.from({length:12},(_,i)=>`<text x="${64+i*80}" y="357" text-anchor="middle">${i+1} 月</text>`).join('')}${points.length>1?`<polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" class="curve"/>`:''}${points.map(p=>`<g role="button" tabindex="0" data-act="reflect-event" data-id="${p.event.id}" aria-label="${esc(visibleTitle(p.event))}，能量 ${p.event.energy}"><circle cx="${p.x}" cy="${p.y}" r="14" class="hit-point"/><circle cx="${p.x}" cy="${p.y}" r="6" class="${p.event.energy>=0?'point-positive':'point-negative'}"/><title>${esc(visibleTitle(p.event))} · ${p.event.energy}</title></g>`).join('')}<text x="52" y="385" class="chart-footnote">事件之間的連線不是全年情緒的連續量測。沒有卡片的月份，不等於 0 分。</text></svg></div>`;}
function reflection(){return `${heading('02 · REFLECTIVE / REALITY','看看起伏，也看看自己。','評的是事件帶來的心理能量，不是人生好壞。低分也可能很重要；高分也不一定要更多。')}
  <div class="toolbar"><label>這次評分的視角 <select id="basis" data-change="basis"><option value="then" ${w.basis==='then'?'selected':''}>回想當時的感受</option><option value="now" ${w.basis==='now'?'selected':''}>現在回看的感受</option></select></label><span>−10 明顯耗損　／　0 中性或混合　／　+10 明顯補充</span></div><div class="panel chart-panel"><div class="section-title"><h2>這一年，不只有一種顏色。</h2><span>${ratedEvents(w).filter(e=>e.energy!==null&&!e.background).length} 個已標記片刻</span></div>${curve()}</div>
  ${note('點選曲線上的事件或下方卡片，標記能量、情緒與回應空間。<b>安排好的／意外發生</b>，和<b>可以怎麼回應</b>是兩個不同問題。')}
  <div class="card-grid section-space">${chronology(w.events).map(e=>eventCard(e,true)).join('')}${w.events.filter(e=>e.background).map(e=>eventCard(e,true)).join('')}</div>${!w.events.length?empty('還沒有片刻','可以回去拾起一張卡，也可以直接探索方向。',btn('拾起片刻','nav','outline','data-page="1"')):''}<div class="panel section-space"><h3>不急著下結論，我先注意到……</h3><p>${esc(w.reflection)||'哪些時候在補充你？哪些事情很重要，卻也需要支持？'}</p>${btn('記下一個觀察','reflection-note','outline')}</div>${next(3,'發現線索')}`;}
function themes(){return `${heading('03 · INTERPRETIVE / GOAL','讓線索浮現，不替自己定型。','從事件分群，或先提出一個詞，都可以。主題不比覆蓋率；沒有歸類的片刻也能很重要。',btn(`${icon('plus')} 新增主題`,'theme','primary'))}
  <div class="segmented" role="group" aria-label="探索主題的入口">${btn('先分群，再命名','theme-mode',themeMode==='bottom'?'selected':'',`data-mode="bottom" aria-pressed="${themeMode==='bottom'}"`)}${btn('先有詞，再找關聯','theme-mode',themeMode==='top'?'selected':'',`data-mode="top" aria-pressed="${themeMode==='top'}"`)}</div>
  <div class="prompt-strip">${icon('theme')}<div>${themeMode==='bottom'?'<b>先把相似片刻放在一起。</b> 新增主題時，先選卡片再命名。它們重要的地方相同嗎？':'<b>先提出一個可以被修正的假設。</b> 詞卡是入口，不是答案。選一個詞，再挑支持與不符合的片刻。'}<div class="tags">${values.map(v=>btn(v,'theme-word','chip',`data-word="${v}"`)).join('')}</div></div></div>
  <div class="card-grid">${w.themes.map(t=>`<article class="panel theme-card"><div class="card-top">${tag('主題假設')}${btn(icon('edit'),'theme','icon-btn',`data-id="${t.id}" aria-label="編輯主題：${esc(t.name)}"`)}</div><h2>${esc(t.name)}</h2><div class="linked-list">${t.eventIds.map(id=>w.events.find(e=>e.id===id)).filter(Boolean).map(e=>`<span>${e.month} 月 · ${esc(visibleTitle(e))}</span>`).join('')||'<span>還沒有關聯片刻</span>'}</div><div class="counter"><small>另一種可能／例外</small><p>${esc(t.alternative)||'還有別的解讀嗎？這個詞有沒有解釋不了的卡片？'}</p>${t.counterIds.map(id=>w.events.find(e=>e.id===id)).filter(Boolean).map(e=>tag(visibleTitle(e))).join('')}</div>${t.note?`<p>${esc(t.note)}</p>`:''}</article>`).join('')}</div>
  ${!w.themes.length?empty('先留下一條線索','不必把每張卡都分類，也不用把每個低谷說成成長。'):''}
  <section class="section-space"><div class="section-title"><div><div class="eyebrow">FROM MEANING TO CHOICE</div><h2>過去的主題，不等於未來的方向。</h2><p>今年可能是「撐住」，接下來可以選擇「求助」。最多先帶走幾個真正想支持的方向。</p></div>${btn(`${icon('plus')} 新增方向`,'direction','outline')}</div><div class="card-grid">${w.directions.map(d=>`<article class="direction-card"><div class="card-top">${icon('flag')}${btn(icon('edit'),'direction','icon-btn',`data-id="${d.id}" aria-label="編輯方向：${esc(d.name)}"`)}</div><h3>${esc(d.name)}</h3><p>${esc(d.why)||'這個方向對我意味著什麼？'}</p><div class="tags">${d.themeIds.map(id=>w.themes.find(t=>t.id===id)?.name).filter(Boolean).map(tag).join('')}</div></article>`).join('')}</div></section>${next(4,'打開不同可能')}`;}
function options(){const r=resourceStatus(w,stress);return `${heading('04 · OPTIONS','同一個在乎，可以有不同走法。','先展開候選路線，再比較代價；不是把第一個答案拆得更細。少做、換個方法、先觀察，都算一條路。',btn(`${icon('plus')} 新增路線`,'route','primary'))}
  <div class="options-top"><div class="prompt-card"><div class="eyebrow">THE POSSIBILITY DECK</div><h2>${prompts[promptIndex]}</h2><p>這是提問，不是答案。可以不採用，也可以寫自己的。</p>${btn(`${icon('review')} 換一個提問`,'draw','outline')}</div><div class="panel"><div class="section-title"><h3>帶得走的資源，才是你的路線圖。</h3>${btn('調整預算','budget','quiet')}</div><div class="resource-grid">${[['hours','每週可用時間','小時'],['money','每月可用預算','元'],['energy','心力／自訂點數','點']].map(([k,t,u])=>`<div class="resource ${r.over.includes(k)?'over':''}"><small>${t}</small><strong>${Number(r.used[k].toFixed(1)).toLocaleString()}</strong><span>/ ${r.limit[k].toLocaleString()} ${u}</span><meter min="0" max="${r.limit[k]||1}" value="${Math.min(r.used[k],r.limit[k]||1)}">${r.used[k]}</meter><small>${r.over.includes(k)?'超過目前可用資源':'保留餘裕，也是一種選擇'}</small></div>`).join('')}</div><label class="checkline"><input type="checkbox" data-change="stress" ${stress?'checked':''}> 壓力測試：可用時間與心力只剩一半</label><small class="muted">只合計選中路線；月預算不變。這是估算，不是心理量表。</small></div></div>
  ${r.over.length?`<div class="banner warning" role="status">這個組合超過${stress?'壓力情境下的':'目前的'}預算。可以取消一條、縮小做法或調整假設；不會扣分。</div>`:''}
  <div class="section-title"><h2>先並排比較，再決定帶走什麼。</h2><span>${w.routes.length} 條候選 · 已選 ${w.routes.filter(r=>r.selected).length} 條</span></div>
  ${w.directions.length===0?note('還沒有方向也沒關係。可以先提出具體路線，再回去命名它支持什麼。'):''}
  <div class="card-grid routes">${w.routes.map(r=>`<article class="panel route-card ${r.selected?'chosen':''}"><div class="card-top">${tag(kinds[r.kind])}${btn(icon('edit'),'route','icon-btn',`data-id="${r.id}" aria-label="編輯路線：${esc(r.title)}"`)}</div><small class="muted">${esc(w.directions.find(d=>d.id===r.directionId)?.name||'方向還在浮現')}</small><h2>${esc(r.title)}</h2><dl><dt>如何支持這個方向</dt><dd>${esc(r.benefit)||'尚未填寫'}</dd><dt>要付出的代價／放棄什麼</dt><dd>${esc(r.tradeoff)||'尚未填寫'}</dd><dt>最小的第一步</dt><dd>${esc(r.firstStep)||'尚未填寫'}</dd></dl><div class="tags">${tag(`${r.hours} 小時 / 週`)}${tag(`${r.money.toLocaleString()} 元 / 月`)}${tag(`${r.energy} 心力`)}</div><div class="counter"><small>遇到阻礙</small><p>${esc(r.barrier)||'哪一種情境可能打亂這條路？'}</p><small>我的備案</small><p>${esc(r.backup)||'縮小或換一種做法，會是什麼？'}</p><small>我的信心 ${r.confidence} / 10</small></div>${r.reason?`<p class="reason">選擇理由：${esc(r.reason)}</p>`:''}${btn(`${icon(r.selected?'check':'plus')} ${r.selected?'已選擇 · 取消':'暫時選這條'}`,'select-route',r.selected?'selected wide':'outline wide',`data-id="${r.id}" aria-pressed="${r.selected}"`)}${r.selected?btn('把這條路帶成實驗','from-route','quiet wide',`data-id="${r.id}"`):''}</article>`).join('')}</div>
  ${!w.routes.length?empty('不是只有增加待辦事項這條路','可以先試三種不同做法，再選擇。比較是邀請，不是硬性通關門檻。',btn('建立一組空白候選路線','route-starters','outline')):''}${note('<b>先不改變，也是一條路。</b> 你可以把「先觀察兩週」寫成路線；也能跳過目標，直接把一段話帶回生活。')}${next(5,'帶走一個小實驗')}`;}
function actions(){return `${heading('05 · DECISION / WILL','不必規劃整個人生，先試一小步。','從方向往下拆，或先寫想做的事、再往上連回方向。這不是意志力契約；做完也要檢查它值不值得。',btn(`${icon('plus')} 新增實驗`,'action','primary'))}
  <div class="two-col"><div class="panel"><div class="eyebrow">TOP DOWN</div><h3>從選好的路線，帶走下一步。</h3><p>方向 → 候選路線 → 成果／行為 → 執行與方向驗收</p>${w.routes.filter(r=>r.selected).map(r=>btn(`${esc(r.title)} ${icon('arrow')}`,'from-route','outline wide',`data-id="${r.id}"`)).join('')||'<small class="muted">還沒選路線；可以回去比較，也可以從右邊開始。</small>'}</div><div class="panel"><div class="eyebrow">BOTTOM UP</div><h3>先知道想做什麼，也可以。</h3><p>具體行動 → 它支持什麼？ → 連到一個或多個方向</p>${btn(`${icon('plus')} 先寫一件想做的事`,'action','outline')}${btn('命名一個方向','direction','quiet')}</div></div>
  <div class="card-grid section-space">${w.actions.map(a=>`<article class="panel action-card"><div class="card-top">${tag(actionTypes[a.type])}${btn(icon('edit'),'action','icon-btn',`data-id="${a.id}" aria-label="編輯實驗：${esc(a.title)}"`)}</div><h2>${esc(a.title)}</h2><div class="tags">${a.directionIds.map(id=>w.directions.find(d=>d.id===id)?.name).filter(Boolean).map(tag).join('')}</div><div class="metric">${esc(periods[a.period])}<strong>${a.type==='boundary'?'最多 ':''}${a.target} <small>${esc(a.unit)}</small></strong></div><dl>${a.objective?`<dt>想支持的目標</dt><dd>${esc(a.objective)}</dd>`:''}${a.result?`<dt>期待的成果／KR</dt><dd>${esc(a.result)}</dd>`:''}<dt>當……就開始</dt><dd>${esc(a.trigger)||'尚未設定'}</dd><dt>執行驗收 · 什麼算完成</dt><dd>${esc(a.definition)||'尚未設定'}</dd><dt>方向驗收 · 值不值得</dt><dd>${esc(a.support)||'尚未設定'}</dd><dt>遇到阻礙時的縮小版本</dt><dd>${esc(a.backup)||'尚未設定'}</dd></dl><div class="card-foot"><small>${a.reviewDate} 回來看看</small>${tag(statuses[a.status])}</div>${btn('記錄這次實驗','review','outline wide',`data-id="${a.id}"`)}</article>`).join('')}</div>
  ${!w.actions.length?empty('先有一個可負擔的實驗，就夠了','也可以不新增目標。把現在需要的支持或界線記在下面。'):''}<div class="panel section-space"><h3>這次，我決定帶走的是……</h3><p>${esc(w.intention)||'可以是一個方向、一句話，或「我先不要新增任何目標」。'}</p>${btn('記下我的選擇','intention','outline')}</div>${next(6,'設定回來看看的方式')}`;}
function reviews(){return `${heading('06 · REVIEW / LEARNING','不是交作業，是再認識自己。','有沒有做，和有沒有支持你在乎的事，是兩個問題。可以繼續、調整、暫停或停止；沒有連勝，也不補交。')}
  ${w.actions.length?`<div class="card-grid">${w.actions.map(a=>`<article class="panel"><div class="card-top">${tag(statuses[a.status])}<small>${['pause','stop'].includes(a.status)?'先留在這裡':a.reviewDate<=today()?'到了回來看看的時間':`${a.reviewDate} 再看看`}</small></div><h2>${esc(a.title)}</h2><p>${esc(periods[a.period])} ${a.type==='boundary'?'最多 ':''}${a.target} ${esc(a.unit)} · ${w.reviews.filter(r=>r.actionId===a.id).length} 次觀察</p><div class="button-row">${btn('記錄一次觀察','review','primary',`data-id="${a.id}"`)}${btn(`${icon('clock')} 行事曆提醒`,'calendar','outline',`data-id="${a.id}"`)}</div></article>`).join('')}</div>`:empty('這裡等你帶著經驗回來','沒有新增目標，也可以完成這趟旅程。',btn('留下我現在的選擇','intention','outline'))}
  <section class="section-space"><div class="section-title"><h2>留下的是學習，不是分數。</h2><span>${w.reviews.length} 次回看</span></div><div class="review-list">${w.reviews.slice().reverse().map(r=>`<article class="panel"><div class="card-top"><span>${r.date} · ${esc(w.actions.find(a=>a.id===r.actionId)?.title||'實驗')}</span>${tag(statuses[r.decision])}</div><div class="two-col"><div><small>執行觀察${r.actual===null?'':` · ${r.actual} ${esc(w.actions.find(a=>a.id===r.actionId)?.unit)}`}</small><p>${esc(r.execution)||'這次沒有留下執行筆記。'}</p></div><div><small>方向觀察 · ${{yes:'有支持',mixed:'有一點，也有代價',no:'不太支持',unknown:'還不確定'}[r.alignment]}</small><p>${esc(r.learning)||'還在理解中。'}</p></div></div><div class="card-foot"><small>${r.nextDate?`${r.nextDate} 下次回顧`:'暫時不排下一次'}</small>${btn('刪除這次觀察','delete','quiet',`data-type="reviews" data-id="${r.id}"`)}</div></article>`).join('')}</div></section>
  <div class="closing"><div class="eyebrow">A SMALL POSSIBILITY IS ENOUGH</div><h2>不用把一年整理成漂亮答案。</h2><p>${esc(w.intention)||'知道自己在乎什麼，並留下一個重新選擇的機會，就已經足夠。'}</p>${btn(`${icon('download')} 帶走我的探索紀錄`,'backup','primary')}</div>`;}

// Native dialogs keep forms keyboard- and touch-accessible without drag-only controls.
function field(label,name,value='',type='text',attrs=''){return `<label class="field"><span>${label}</span><input type="${type}" name="${name}" value="${esc(value)}" ${type==='text'?'maxlength="120"':''} ${attrs}></label>`;}
function area(label,name,value='',placeholder=''){return `<label class="field"><span>${label}</span><textarea name="${name}" rows="3" maxlength="3000" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;}
function select(label,name,value,items){return `<label class="field"><span>${label}</span><select name="${name}">${Object.entries(items).map(([k,v])=>`<option value="${esc(k)}" ${String(value)===k?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function checks(label,name,items,selected=[]){return `<fieldset class="field check-group"><legend>${label}</legend>${items.map(([id,label])=>`<label class="checkline"><input type="checkbox" name="${name}" value="${esc(id)}" ${selected.includes(id)?'checked':''}><span>${esc(label)}</span></label>`).join('')||'<small class="muted">目前還沒有可關聯的卡片；可以稍後再連結。</small>'}</fieldset>`;}
function openDialog(title,body,kind='',id='',wide=false){const d=$('#dialog');if(!d.open)lastFocus=document.activeElement;d.innerHTML=`<div class="dialog-head"><div><div class="eyebrow">LIFE ATLAS · YOUR OWN PACE</div><h2 id="dialog-title">${title}</h2></div>${btn(icon('close'),'close','icon-btn','aria-label="關閉對話框"')}</div><form id="editor" data-kind="${kind}" data-id="${id}"><div class="dialog-body">${body}<p id="form-error" class="form-error" role="alert"></p></div>${kind?`<div class="dialog-actions">${id&&['events','themes','directions','routes','actions'].includes(kind)?btn(icon('trash')+' 刪除','delete','quiet danger',`data-type="${kind}" data-id="${id}"`):'<span></span>'}<div>${btn('先不儲存','close','outline')}<button type="submit" class="btn primary">${kind==='review'?'留下觀察':'儲存'}</button></div></div>`:''}</form>`;d.classList.toggle('wide-dialog',wide);if(!d.open)d.showModal();d.scrollTop=0;}
function close(){const d=$('#dialog');d.close();lastFocus?.isConnected&&lastFocus.focus();}
function editEvent(id='',background=false){let e=w.events.find(e=>e.id===id)||newEvent(month);if(!id){e.background=background;e.order=Math.min(3,w.events.filter(x=>!x.background&&x.month===month).length+1);}
  openDialog(id?'再看這個片刻':background?'記下一段日常背景':'拾起一個片刻',`${note('這一站先記事實。例如「連續兩週晚上十點下班」，而不是先說「我是個失敗的人」。感受留到下一站。')}${field('給片刻一個名字 *','title',e.title,'text','required')}<div class="two-col">${select('月份','month',e.month,Object.fromEntries(Array.from({length:12},(_,i)=>[i+1,`${i+1} 月`])))}${select('月內順序','order',e.order,{1:'第一個',2:'第二個',3:'第三個'})}</div>${area('發生了什麼？','fact',e.fact,'誰在場？做了什麼？哪件事發生了變化？')}${select('幫助回憶的線索','source',e.source,{memory:'記憶',calendar:'行事曆',photo:'照片',message:'訊息',other:'其他'})}<label class="checkline"><input type="checkbox" name="background" ${e.background?'checked':''}> 這是持續發生的日常，不占每月 3 張名額</label><label class="checkline"><input type="checkbox" name="private" ${e.private?'checked':''}> 遮住卡片文字（月份與分數仍可見；不是加密）</label>`,'events',id);}
function reflectEvent(id){const stored=w.events.find(e=>e.id===id);if(!stored)return;const e={...stored,energy:w.basis==='now'?stored.energyNow:stored.energy};openDialog('這個片刻，如何影響了你？',`<h3>${esc(e.title)}</h3><p>${esc(e.fact)}</p><div class="energy-input"><label class="field"><span>心理能量 <output id="energy-output">${e.energy===null?'尚未評分':e.energy}</output></span><input name="energy" type="range" min="-10" max="10" step="1" value="${e.energy??0}"></label><div class="range-labels"><span>−10 耗損</span><span>0 中性／混合</span><span>+10 補充</span></div><label class="checkline"><input name="unrated" type="checkbox" ${e.energy===null?'checked':''}> 目前不評分，先留白</label></div><fieldset class="field"><legend>我感受到……（可複選；不是心理測驗）</legend><div class="emotion-grid">${emotions.map(t=>`<label class="emotion-chip"><input type="checkbox" name="emotions" value="${t}" ${e.emotions.includes(t)?'checked':''}><span>${t}</span></label>`).join('')}</div></fieldset>${field('自己的情緒詞（用頓號分隔）','customEmotions',e.emotions.filter(t=>!emotions.includes(t)).join('、'))}<div class="two-col">${select('是安排好的，還是意外？','planned',e.planned,planned)}${select('接下來，我能怎麼回應？','control',e.control,controls)}</div>${area('這件事重要在哪裡？也可以不知道。','meaning',e.meaning)}${note('意外不等於不可控；有計畫也不代表結果都該由你負責。能量低的經驗，不需要被改寫成正向故事。')}`,'reflect',id);}
function editTheme(id='',word=''){const t=w.themes.find(t=>t.id===id)||newTheme();if(word)t.name=word;const eventItems=w.events.map(e=>[e.id,`${e.background?'日常':e.month+' 月'} · ${visibleTitle(e)}`]);const nameField=field('暫時怎麼稱呼這組片刻？ *','name',t.name,'text','required');openDialog('提出一個主題假設',`${themeMode==='top'?nameField:''}${checks('哪些片刻讓你想到同一件事？','eventIds',eventItems,t.eventIds)}${themeMode==='bottom'?nameField:''}${checks('哪些片刻不太符合，或值得另外保留？','counterIds',eventItems,t.counterIds)}${area('另一種合理的解讀是……','alternative',t.alternative,'不必推翻自己；只是留下重新理解的空間。')}${area('我先記下的觀察','note',t.note)}`,'themes',id);}
function editDirection(id=''){const d=w.directions.find(d=>d.id===id)||newDirection();openDialog('選擇接下來想支持的方向',`${field('我想如何生活／行動？ *','name',d.name,'text','required')}${area('它為什麼對我重要？哪些不是我的期待？','why',d.why)}${checks('這個方向和哪些過去主題有關？（可複選，也可不選）','themeIds',w.themes.map(t=>[t.id,t.name]),d.themeIds)}${note('今年常發生的事，不必成為明年的目標。喜歡一件事本身，就可以是理由。')}`,'directions',id);}
function editRoute(id=''){const r=w.routes.find(r=>r.id===id)||newRoute(w.directions[0]?.id||'');openDialog('探索一條不同的路',`${field('路線名稱 *','title',r.title,'text','required')}<div class="two-col">${select('支持哪個方向？','directionId',r.directionId,{'':'方向還在浮現',...Object.fromEntries(w.directions.map(d=>[d.id,d.name]))})}${select('這是哪種可能？','kind',r.kind,kinds)}</div>${area('它怎麼支持這個方向？','benefit',r.benefit)}${area('要付出什麼代價？或放棄什麼？','tradeoff',r.tradeoff)}${area('最小的第一步','firstStep',r.firstStep)}<div class="three-col">${field('每週時數','hours',r.hours,'number','min="0" max="168" step="0.5" required')}${field('每月費用（元）','money',r.money,'number','min="0" max="1000000000" step="1" required')}${field('心力點數','energy',r.energy,'number','min="0" max="100" step="1" required')}</div>${area('什麼情境可能打亂計畫？','barrier',r.barrier)}${area('時間減半時的縮小／替代版本','backup',r.backup)}${field('我目前的信心（0–10）','confidence',r.confidence,'number','min="0" max="10" step="1" required')}${area('比較之後，選擇或不選這條的理由','reason',r.reason)}`,'routes',id);}
function editAction(id='',routeId=''){const r=w.routes.find(r=>r.id===routeId);const a=w.actions.find(a=>a.id===id)||{...newAction(routeId,r?.directionId?[r.directionId]:[]),title:(r?.firstStep||r?.title||'').slice(0,120),obstacle:r?.barrier||'',backup:r?.backup||''};openDialog('設計一個帶得走的小實驗',`${field('實驗名稱 *','title',a.title,'text','required')}${select('它屬於哪一類？','type',a.type,actionTypes)}${note('成果目標可寫 Objective／KR；習慣、界線與流程不必硬套 OKR。下面的數量是你自行定義的驗收，不是人生分數。')}${checks('它支持哪些方向？（可以多對多）','directionIds',w.directions.map(d=>[d.id,d.name]),a.directionIds)}${area('想支持的目標／Objective','objective',a.objective)}${area('期待成果／Key Result（不是活動清單；可留白）','result',a.result)}<div class="three-col">${select('時間頻率','period',a.period,periods)}${field('數量（界線類為上限）','target',a.target,'number','min="0" max="1000000000" step="0.5" required')}${field('單位','unit',a.unit,'text','required')}</div>${area('開始線索：當……，我就…… *','trigger',a.trigger,'例如：週日打開行事曆，就先保留週三的一小時。')}${area('執行驗收：怎樣才算完成？ *','definition',a.definition)}${area('方向驗收：如何知道它真的支持我？ *','support',a.support,'除了有沒有出席，這件事帶來了享受、連結，還是壓力？')}${area('預想到的阻礙','obstacle',a.obstacle)}${area('縮小版本／備案（不冒充原版完成）','backup',a.backup)}<div class="two-col">${field('開始日期','start',a.start,'date','required')}${field('回來看看的日期','reviewDate',a.reviewDate,'date','required')}</div>${field('我目前的信心（0–10）','confidence',a.confidence,'number','min="0" max="10" required')}${area('需要的資源、支持或其他筆記','notes',a.notes)}<input type="hidden" name="routeId" value="${esc(a.routeId)}">`,'actions',id,true);}
function editReview(actionId){const a=w.actions.find(a=>a.id===actionId);if(!a)return;openDialog('留下一次觀察',`<h3>${esc(a.title)}</h3><p>${esc(periods[a.period])} ${a.type==='boundary'?'最多 ':''}${a.target} ${esc(a.unit)}；這不是必須達標的考試。</p><div class="two-col">${field('觀察日期','date',today(),'date','required')}${field(`這次記錄的數量（${esc(a.unit)}；可留白）`,'actual','','number','min="0" max="1000000000" step="0.5"')}</div>${area('執行觀察：這次實際發生了什麼？','execution','','是哪個期間？完整做法、縮小版本，還是沒有做？')}${select('方向觀察：它有支持原本在乎的事嗎？','alignment','unknown',{unknown:'還不確定',yes:'有支持',mixed:'有一點，也有代價',no:'不太支持'})}${area('我學到了什麼？想如何調整？','learning')}${select('下一步的決定','decision','continue',{continue:'繼續試試',adjust:'調整做法',pause:'先暫停',stop:'停止這個實驗'})}${field('下次回顧（暫停／停止可留白）','nextDate',afterDays(14),'date')}`,'review',actionId);}
function backupDialog(){openDialog('把記錄留在自己手上',`${note('資料只存在這個瀏覽器；清除網站資料、換裝置或私密瀏覽結束後可能消失。備份不會加密，請妥善保管。')}<section><h3>完整備份 · JSON</h3><p>包含本年度所有內容，<b>包含被遮住的卡片</b>。可匯入另一台裝置繼續；不是分享用報告。</p>${btn(`${icon('download')} 匯出本年度完整 JSON`,'export-json','primary')}</section><hr><section><h3>匯入本年度備份</h3><p>先驗證格式，再確認覆蓋該年份；其他年度不變。上限 2 MB，不會上傳檔案。</p><label class="btn outline file-label">選擇 JSON 備份<input type="file" accept=".json,application/json" id="import-file"></label></section><hr><section><h3>帶走能量圖</h3><p>SVG 只輸出月份、座標與分數，不包含事件名稱或筆記。圖像仍屬個人資料。</p>${btn('匯出能量曲線 SVG','export-svg','outline')}</section><hr><section><h3>移除此年度的本機記錄</h3><p>只清除 ${w.year} 年；不影響其他年度。刪除前請先備份。</p>${btn('清除此年度','reset','outline danger')}</section>`);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function exportSvg(){const points=chartPoints(ratedEvents(w));download(`life-atlas-${w.year}-energy.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="1040" height="440" viewBox="0 0 1040 440"><rect width="1040" height="440" fill="#f6f5f0"/><g font-family="sans-serif" font-size="13" fill="#34564a"><text x="44" y="28">${w.year} Life Atlas / Event energy, not a continuous mood measurement</text>${[-10,-5,0,5,10].map(n=>`<path d="M45 ${210-n*13}H1000" stroke="#dce1d5"/><text x="12" y="${215-n*13}">${n}</text>`).join('')}${Array.from({length:12},(_,i)=>`<text x="${64+i*80}" y="390">${i+1}</text>`).join('')}<polyline points="${points.map(p=>`${p.x},${p.y+20}`).join(' ')}" fill="none" stroke="#245e52" stroke-width="2"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y+20}" r="5" fill="#245e52"/>`).join('')}<text x="45" y="425">Unrecorded months are not zero. Event names and notes are intentionally omitted.</text></g></svg>`,'image/svg+xml');}
function calendar(id){const a=w.actions.find(a=>a.id===id);if(!a)return;const dt=a.reviewDate.replaceAll('-',''),end=afterDays(1,a.reviewDate).replaceAll('-','');download('life-atlas-review.ics',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Life Atlas//Reflection//ZH\r\nCALSCALE:GREGORIAN\r\nBEGIN:VEVENT\r\nUID:${a.id}@life-atlas.local\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z')}\r\nDTSTART;VALUE=DATE:${dt}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:Life Atlas - Review a small experiment\r\nDESCRIPTION:Return to your Life Atlas on your own device.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`,'text/calendar');toast('提醒檔已匯出；需由你匯入行事曆；通知依該行事曆設定。標題不含個人實驗內容。');}
function help(){openDialog('玩法與界線',`<p>這是一場單人反思遊戲，不是心理測驗、治療或競賽。</p><ol class="help-list"><li><b>拾起片刻：</b>每月 0–3 張；先記事實，日常另放。</li><li><b>看見起伏：</b>能量 −10 到 +10；評分、情緒詞皆可留白。</li><li><b>發現線索：</b>自己命名、找支持與例外；再選未來方向。</li><li><b>打開可能：</b>比較不同路線、代價與資源；可以先觀察。</li><li><b>帶走實驗：</b>明確開始線索、頻率、兩種驗收與備案。</li><li><b>回來看看：</b>留下經驗，再決定繼續、調整、暫停或停止。</li></ol>${note('所有關卡都能跳過。不分享、不命名、不新增行動，都是合法結束方式。情緒難以承受時先停下，尋求你信任的人或專業支持。')}<h3>關於隱私</h3><p>不登入、不追蹤、不傳送反思內容。LocalStorage 不是加密保險箱；同一裝置的使用者可讀取資料。多人共用裝置請備份並清除記錄。多分頁衝突會暫停儲存。</p><h3>兩個 O，不混在一起</h3><p>ORID 的 Objective 放在第一站，先記事實；GROW 的 Options 放在第四站，先比較替代路線再選行動。這是設計框架，不是宣稱本遊戲經過臨床驗證。</p>`);}
async function handle(act,el){const id=el.dataset.id||'';
  switch(act){
    case'nav':page=Number(el.dataset.page);render();break;
    case'month':month=Number(el.dataset.month);render(false);break;
    case'privacy':hideAll=!hideAll;render(false);break;
    case'event':editEvent(id);break;case'background':editEvent('',true);break;case'reflect-event':reflectEvent(id);break;
    case'theme':editTheme(id);break;case'theme-word':themeMode='top';editTheme('',el.dataset.word);break;
    case'theme-mode':themeMode=el.dataset.mode;render(false);break;case'direction':editDirection(id);break;case'route':editRoute(id);break;
    case'action':editAction(id);break;case'from-route':editAction('',id);break;case'review':editReview(id);break;
    case'draw':promptIndex=(promptIndex+1)%prompts.length;render(false);break;
    case'select-route':{const r=w.routes.find(r=>r.id===id);if(r.selected){update(()=>r.selected=false);}else{openDialog('比較之後，先帶這條路',`<h3>${esc(r.title)}</h3><p>同一方向還有 ${w.routes.filter(x=>x.id!==r.id&&x.directionId===r.directionId).length} 條候選。先比較支持方式、代價與備案，再暫時選擇。</p>${area('為什麼先選這條？（可稍後補）','reason',r.reason)}${note('這不是永久承諾。選了還能取消；超過資源也可以再縮小。')}`,'choose-route',id);}break;}
    case'route-starters':update(()=>{['more','less','observe'].forEach((kind,i)=>w.routes.push({...newRoute(w.directions[0]?.id||''),kind,title:['多做一點：待我命名','少做一點：待我命名','先觀察：待我命名'][i]}));});break;
    case'budget':openDialog('我目前帶得走的資源',`${note('請填扣除既有責任後，願意留給這些新路線的餘額。心力點數是你的估算，不是心理測量。')}${field('每週可用時間（小時）','hours',w.budget.hours,'number','min="0" max="168" step="0.5" required')}${field('每月可用預算（元）','money',w.budget.money,'number','min="0" max="1000000000" required')}${field('心力點數上限','energy',w.budget.energy,'number','min="0" max="100" required')}`,'budget');break;
    case'reflection-note':openDialog('留下一個觀察',area('我先注意到……','reflection',w.reflection),'reflection');break;
    case'intention':openDialog('我現在的選擇',area('這次，我決定帶走的是……','intention',w.intention,'先不要新增任何目標，也是一個完整答案。'),'intention');break;
    case'year':openDialog('打開另一年的探索桌',`${field('回顧年份','year',w.year,'number','min="1900" max="2100" step="1" required')}<p>每一年分開保留，不會把目前卡片改成新年份。你已記錄的年份：${Object.keys(envelope.years).join('、')||'尚無'}。</p>${demo?note('示範模式只切換示範年份；不會動到正式資料。'):''}`,'year');break;
    case'demo':if(!demo){saved=structuredClone(w);w=makeDemo();demo=true;stress=false;}page=1;month=1;render();break;
    case'exit-demo':if(demo){w=saved;demo=false;saved=null;stress=false;page=0;render();}break;
    case'help':help();break;case'backup':backupDialog();break;case'close':close();break;
    case'export-json':download(`life-atlas-${w.year}${demo?'-demo':''}.json`,JSON.stringify(w,null,2),'application/json');toast('備份包含遮住的內容，請妥善保管。');break;
    case'export-svg':exportSvg();break;case'calendar':calendar(id);break;
    case'delete':{const type=el.dataset.type;openDialog('確認刪除這張卡片？',`<p>這個操作無法復原。關聯會解除，但其他主題、路線和實驗會保留。${type==='actions'?'此實驗的回顧紀錄也會一起刪除。':''}</p><div class="button-row">${btn('先保留','close','outline')}${btn('確認刪除','confirm-delete','primary danger',`data-type="${type}" data-id="${id}"`)}</div>`);break;}
    case'confirm-delete':w=deleteEntity(w,el.dataset.type,id);persist();close();render(false);toast('卡片已刪除，其他關聯已整理。');break;
    case'reset':openDialog('清除此年度前，請確認',`<p>這會清除 ${w.year} 年全部卡片與回顧，其他年度不變。沒有伺服器副本可復原。示範模式只清除示範。</p><div class="button-row">${btn('回去備份','backup','outline')}${btn(`確認清除 ${w.year} 年`,'confirm-reset','primary danger')}</div>`);break;
    case'confirm-reset':w=createWorkspace(w.year);persist();close();page=0;render();break;
    case'conflict':openDialog('先保留，再選擇',`<p>自動儲存已暫停。本分頁的內容還在記憶體；重新載入會採用另一分頁的版本。請先匯出本分頁需要保留的年度。</p><div class="button-row">${btn('匯出本分頁 JSON','export-json','primary')}${btn('重新載入另一分頁版本','reload','outline')}</div>`);break;
    case'reload':location.reload();break;
  }
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-act]');if(!el)return;e.preventDefault();handle(el.dataset.act,el);});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('svg [role="button"]')){e.preventDefault();handle(e.target.dataset.act,e.target);}});
document.addEventListener('input',e=>{if(e.target.name==='energy'&&e.target.type==='range'){const form=e.target.form;form.elements.unrated.checked=false;$('#energy-output').textContent=e.target.value;}});
document.addEventListener('change',async e=>{const t=e.target;
  if(t.dataset.change==='basis')update(()=>{w.basis=t.value;toast('已切換評分視角；當時與現在的分數分開保留，不會清空。');});
  if(t.dataset.change==='stress'){stress=t.checked;render(false);}
  if(t.name==='unrated')$('#energy-output').textContent=t.checked?'尚未評分':t.form.elements.energy.value;
  if(t.id==='import-file'&&t.files[0]){try{if(t.files[0].size>2_000_000)throw Error('檔案超過 2 MB。');const candidate=parseBackup(await t.files[0].text());
    openDialog('驗證完成，確認匯入？',`<p>${candidate.year} 年 · ${candidate.events.length} 個片刻 · ${candidate.actions.length} 個實驗。${demo?'目前在示範模式；只替換示範內容，不保存。':envelope.years[candidate.year]?'該年度已存在，匯入會覆蓋它，請先備份。':'將打開這一年度，不影響其他年度。'}</p><div class="button-row">${btn('取消','close','outline')}<button class="btn primary" type="button" id="confirm-import">確認匯入</button></div>`);
    $('#confirm-import').onclick=()=>{w=candidate;persist();close();page=1;render();toast('備份已匯入。');};
  }catch(err){toast(err.message);t.value='';}}
});
document.addEventListener('submit',e=>{if(e.target.id!=='editor')return;e.preventDefault();const f=e.target,kind=f.dataset.kind,id=f.dataset.id,fd=new FormData(f),s=k=>String(fd.get(k)||'').trim(),n=k=>Number(fd.get(k)),list=k=>fd.getAll(k).map(String);
  try{let row,collection=kind;const old=Array.isArray(w[kind])?w[kind].find(x=>x.id===id):undefined;
    if(kind==='events'){row={...(old||newEvent()),title:s('title'),fact:s('fact'),month:n('month'),order:n('order'),source:s('source'),background:fd.has('background'),private:fd.has('private')};if(!row.background&&w.events.filter(x=>!x.background&&x.month===row.month&&x.id!==id).length>=3)throw Error('這個月已有三張片刻，可以換月份或改放日常背景。');}
    if(kind==='reflect'){collection='events';row={...w.events.find(x=>x.id===id),[w.basis==='now'?'energyNow':'energy']:fd.has('unrated')?null:n('energy'),emotions:[...new Set([...list('emotions'),...s('customEmotions').split(/[、,，]/).filter(Boolean)])],planned:s('planned'),control:s('control'),meaning:s('meaning')};}
    if(kind==='themes')row={...(old||newTheme()),name:s('name'),eventIds:list('eventIds'),counterIds:list('counterIds'),alternative:s('alternative'),note:s('note')};
    if(kind==='directions')row={...(old||newDirection()),name:s('name'),themeIds:list('themeIds'),why:s('why')};
    if(kind==='routes')row={...(old||newRoute()),title:s('title'),directionId:s('directionId'),kind:s('kind'),benefit:s('benefit'),tradeoff:s('tradeoff'),firstStep:s('firstStep'),barrier:s('barrier'),backup:s('backup'),hours:n('hours'),money:n('money'),energy:n('energy'),confidence:n('confidence'),reason:s('reason')};
    if(kind==='actions'){if(!s('trigger')||!s('definition')||!s('support'))throw Error('請補上開始線索、執行驗收與方向驗收；也可以先不儲存，回去想想。');row={...(old||newAction()),title:s('title'),type:s('type'),directionIds:list('directionIds'),routeId:s('routeId'),objective:s('objective'),result:s('result'),target:n('target'),unit:s('unit'),period:s('period'),trigger:s('trigger'),definition:s('definition'),obstacle:s('obstacle'),backup:s('backup'),support:s('support'),start:s('start'),reviewDate:s('reviewDate'),confidence:n('confidence'),notes:s('notes')};}
    let candidate=structuredClone(w);
    if(kind==='events')candidate.events=upsertEvent(candidate.events,row);
    else if(row){const i=candidate[collection].findIndex(x=>x.id===row.id);if(i>=0)candidate[collection][i]=row;else candidate[collection].push(row);}
    if(kind==='choose-route'){const r=candidate.routes.find(r=>r.id===id);r.selected=true;r.reason=s('reason');}
    if(kind==='budget')candidate.budget={hours:n('hours'),money:n('money'),energy:n('energy')};
    if(kind==='reflection')candidate.reflection=s('reflection');if(kind==='intention')candidate.intention=s('intention');
    if(kind==='review'){if(['continue','adjust'].includes(s('decision'))&&!s('nextDate'))throw Error('繼續或調整時，請留下一個下次回顧日期。');if(s('nextDate')&&s('nextDate')<s('date'))throw Error('下次回顧不能早於本次觀察日期。');candidate.reviews.push({id:uid(),actionId:id,date:s('date'),actual:s('actual')===''?null:n('actual'),execution:s('execution'),alignment:s('alignment'),learning:s('learning'),decision:s('decision'),nextDate:s('nextDate')});const a=candidate.actions.find(a=>a.id===id);a.status=s('decision');if(s('nextDate'))a.reviewDate=s('nextDate');}
    if(kind==='year'){const year=n('year');if(!Number.isInteger(year)||year<1900||year>2100)throw Error('年份需要介於 1900 與 2100。');candidate=demo?makeDemo(year):envelope.years[year]||createWorkspace(year);}
    w=validateWorkspace(candidate);persist();close();render(false);toast(demo?'示範已更新，不影響正式資料。':memoryWarning||conflict?'已留在本分頁，請先備份。':'已存在這台裝置。');
  }catch(err){$('#form-error').textContent=err.message;$('#form-error').scrollIntoView({block:'nearest'});}
});
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue!==storageStamp){conflict=true;render(false);}});
window.addEventListener('beforeunload',e=>{if((memoryWarning||conflict)&&!demo&&w.updatedAt){e.preventDefault();e.returnValue='';}});
render(false);
